#!/bin/bash -e

IMAGE_NAME=$3
DOCKER_FILE=$1
DOCKER_FILE_CONTEXT=$2

docker build --force-rm -t "$IMAGE_NAME" -f $DOCKER_FILE $DOCKER_FILE_CONTEXT
docker tag "$IMAGE_NAME" $IMAGE_NAME:$BITBUCKET_BRANCH
docker tag "$IMAGE_NAME" $IMAGE_NAME:$BITBUCKET_BRANCH-$BITBUCKET_BUILD_NUMBER-$BITBUCKET_COMMIT_SHORT

docker push "$IMAGE_NAME"
